### ISSUE TITLE
I see SQL injection vulnerabilities

### ISSUE THREAD

**Issue by jacobsteffler** [team1306/sandman-scouting#5]
:(

**Comment by samr28** [comment]
Are you on the release 5.0.0 branch? If so, can you show me where? I've been fixing it where I see it but have probably missed some places.

It will be merged into master at some point.

**Comment by jacobsteffler** [comment]
Ah, I was in master but I'm looking at v5 now.
What exactly have you changed for this? The diff between these branches two branches is pretty large, so it's hard to see exactly what's going on.

The one that really caught my eye is near the top of remove.php. If the ID is given as `"0 OR 1=1"` then the full query will be ``"DELETE FROM `matchdata` WHERE id = 0 OR 1=1"`` -- this will delete every row.
These is a risk every time a query is constructed from `$variables`. There's another example in sendDBg.php where a large query is constructed from POSTed data.

Since you have changed a lot, though, I'm not sure if these files are even relevant anymore.
But anyway, security isn't a big deal here, as long as you can rely on everyone being GP, which I think is fair.
I just think security is really fun.

**Comment by samr28** [comment]
Yeah that's pretty bad. I totally forgot about that. `remove.php` is still used. If I changed this to POST instead with hidden input elements with the ID, would that be safe? Is there a way to modify these hidden input elements client side?

`<input id="id" name="id" type="hidden" value="itemID">`

For `sendDBg.php`, I send all of the user text input by calling the php function: `mysqli_real_escape_string()`. All of these queries should be using PDOs but I'm not super familiar with them so I'll have to do some reading to figure out how to use them.

Last year the motto was "GP is our security." I don't want that again this season. I'll try to remove all of the old files that aren't used anymore so that we can go through the actually used things and make them more secure. Thanks for helping me improve my code 👍

**Comment by jacobsteffler** [comment]
Hidden fields are not inherently secure, and they still need to be validated like any other field.
There's a good SO question [here](https://stackoverflow.com/questions/16293741/original-purpose-of-input-type-hidden), but the two main purposes for hidden fields are:

- When generating the HTML, the server will auto-populate this field with a state-maintaining value. When you send back the form, the server will use that value to understand the context of the form.
- Have the JavaScript populate this field with some secret, which is probably stored as a cookie. The server will reject any form with an invalid secret. An attacker would need access to the victim's client cookie in order to submit a fraudulent form.

Most modern browsers have a HTML inspector to fiddle with the webpage. You can alter hidden fields here. Even if you didn't have a web browser, you could use a simple HTTP-compliant tool to generate custom messages, and the server wouldn't be able to tell the difference.

Using an escaped string should always be safe, unless you forget to do it!
Because of that, using prepared statements is the way to go. Once you get in the habit of it, it's second-nature. I'm not super familiar with PHP, but it looks like PDO is a common wrapper around different database technologies.
Here's a good tutorial for doing prepared statements with plain MySQLi, as well as PDO: [https://www.w3schools.com/php/php_mysql_prepared_statements.asp](https://www.w3schools.com/php/php_mysql_prepared_statements.asp)

Even though security isn't critical here, I like your mindset this year!
